version: "3.5"
services:
  mysqlservice:
    image: mysql:5.5
    ports:
      - 3306:3306
    container_name: mysql-container
    network_mode: host
    hostname: localhost
    environment:
      MYSQL_ROOT_PASSWORD: Siddhesh@03
      MYSQL_USERNAME: user
      MYSQL_PASSWORD: Siddhesh@03
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

mongodbservice:
  image: mongo:latest
  container_name: mongo-container
  network_mode: host
  hostname: localhost
  ports:
    - 27017:27017

Authenticationservice:
  container_name: todo-authentication-service
  build: AuthenticationService/
  hostname: localhost
  network_mode: host
  ports:
    - 8081:8081
  depends_on:
    - mysqlservice
    - eurekaServer
    - cloudapiservice
  restart: always

Managerservice:
  container_name: todo-manager-service
  build: ManagerService/
  hostname: localhost
  network_mode: host
  ports:
    - 8082:8082
  depends_on:
    - mongodbservice
    - eurekaServer
    - cloudapiservice
  restart: always

Reminderservice:
  container_name: todo-task-service
  build: TasksService/
  network_mode: localhost
  ports:
    -8083:8083
  depends_on:
    - mongodbservice
    - eurekaServer
    - cloudapiservice
    restart: always

Archiveservice:
  container_name: todo-archive-service
  build: ArchiveService/
  network_mode: localhost
  ports:
    -8084:8084
  depends_on:
    - mongodbservice
    - eurekaServer
    - cloudapiservice
    restart: always


Gatewayservice:
  image: cloud-api-service
  build: spring_api_gateway/
  restart: always
  network_mode: host
  #hostname: localhost
  ports:
    - 9000:9000
  environment:
    API_GATEWAY_PORT: 9000
    EUREKA_SERVER_IP: localhost
    EUREKA_SERVER_PORT: 8761
  depends_on:
    - eurekaServer


EurekaServer:
  image: eureka-service
  build: EurekaServer/
  restart: always
  network_mode: host
  #hostname: localhost
  environment:
    EUREKA_SERVER_PORT: 8761
  ports:
    - 8761:8761